/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarroomRouteImport } from './routes/warroom'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SentinelRouteImport } from './routes/sentinel'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogbookRouteImport } from './routes/logbook'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as CommandRouteImport } from './routes/command'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'
import { Route as AppAskRouteImport } from './routes/app.ask'

const WarroomRoute = WarroomRouteImport.update({
  id: '/warroom',
  path: '/warroom',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SentinelRoute = SentinelRouteImport.update({
  id: '/sentinel',
  path: '/sentinel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogbookRoute = LogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/app/ask',
  path: '/app/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/architecture': typeof ArchitectureRoute
  '/command': typeof CommandRoute
  '/decisions': typeof DecisionsRoute
  '/investigations': typeof InvestigationsRoute
  '/logbook': typeof LogbookRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/procurement': typeof ProcurementRoute
  '/sentinel': typeof SentinelRoute
  '/simulator': typeof SimulatorRoute
  '/twin': typeof TwinRoute
  '/warroom': typeof WarroomRoute
  '/app/ask': typeof AppAskRoute
  '/assets/$id': typeof AssetsIdRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/architecture': typeof ArchitectureRoute
  '/command': typeof CommandRoute
  '/decisions': typeof DecisionsRoute
  '/investigations': typeof InvestigationsRoute
  '/logbook': typeof LogbookRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/procurement': typeof ProcurementRoute
  '/sentinel': typeof SentinelRoute
  '/simulator': typeof SimulatorRoute
  '/twin': typeof TwinRoute
  '/warroom': typeof WarroomRoute
  '/app/ask': typeof AppAskRoute
  '/assets/$id': typeof AssetsIdRoute
  '/assets': typeof AssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/architecture': typeof ArchitectureRoute
  '/command': typeof CommandRoute
  '/decisions': typeof DecisionsRoute
  '/investigations': typeof InvestigationsRoute
  '/logbook': typeof LogbookRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/procurement': typeof ProcurementRoute
  '/sentinel': typeof SentinelRoute
  '/simulator': typeof SimulatorRoute
  '/twin': typeof TwinRoute
  '/warroom': typeof WarroomRoute
  '/app/ask': typeof AppAskRoute
  '/assets/$id': typeof AssetsIdRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/architecture'
    | '/command'
    | '/decisions'
    | '/investigations'
    | '/logbook'
    | '/login'
    | '/platform'
    | '/procurement'
    | '/sentinel'
    | '/simulator'
    | '/twin'
    | '/warroom'
    | '/app/ask'
    | '/assets/$id'
    | '/assets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/architecture'
    | '/command'
    | '/decisions'
    | '/investigations'
    | '/logbook'
    | '/login'
    | '/platform'
    | '/procurement'
    | '/sentinel'
    | '/simulator'
    | '/twin'
    | '/warroom'
    | '/app/ask'
    | '/assets/$id'
    | '/assets'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alerts'
    | '/architecture'
    | '/command'
    | '/decisions'
    | '/investigations'
    | '/logbook'
    | '/login'
    | '/platform'
    | '/procurement'
    | '/sentinel'
    | '/simulator'
    | '/twin'
    | '/warroom'
    | '/app/ask'
    | '/assets/$id'
    | '/assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CommandRoute: typeof CommandRoute
  DecisionsRoute: typeof DecisionsRoute
  InvestigationsRoute: typeof InvestigationsRoute
  LogbookRoute: typeof LogbookRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  ProcurementRoute: typeof ProcurementRoute
  SentinelRoute: typeof SentinelRoute
  SimulatorRoute: typeof SimulatorRoute
  TwinRoute: typeof TwinRoute
  WarroomRoute: typeof WarroomRoute
  AppAskRoute: typeof AppAskRoute
  AssetsIdRoute: typeof AssetsIdRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warroom': {
      id: '/warroom'
      path: '/warroom'
      fullPath: '/warroom'
      preLoaderRoute: typeof WarroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentinel': {
      id: '/sentinel'
      path: '/sentinel'
      fullPath: '/sentinel'
      preLoaderRoute: typeof SentinelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logbook': {
      id: '/logbook'
      path: '/logbook'
      fullPath: '/logbook'
      preLoaderRoute: typeof LogbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ask': {
      id: '/app/ask'
      path: '/app/ask'
      fullPath: '/app/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  ArchitectureRoute: ArchitectureRoute,
  CommandRoute: CommandRoute,
  DecisionsRoute: DecisionsRoute,
  InvestigationsRoute: InvestigationsRoute,
  LogbookRoute: LogbookRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  ProcurementRoute: ProcurementRoute,
  SentinelRoute: SentinelRoute,
  SimulatorRoute: SimulatorRoute,
  TwinRoute: TwinRoute,
  WarroomRoute: WarroomRoute,
  AppAskRoute: AppAskRoute,
  AssetsIdRoute: AssetsIdRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
